-- Oracle schema for Utility Billing Engine
-- Meter-to-Cash data model

CREATE SEQUENCE ACCOUNT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE METER_READ_SEQ START WITH 1 INCREMENT BY 50;
CREATE SEQUENCE BILL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PAYMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE TARIFF_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE ACCOUNTS (
    ID NUMBER(19) PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    CUSTOMER_NAME VARCHAR2(255) NOT NULL,
    SERVICE_ADDRESS VARCHAR2(500),
    SERVICE_CLASS VARCHAR2(20) NOT NULL,
    BILLING_CYCLE NUMBER(2) NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    METER_NUMBER VARCHAR2(30),
    BALANCE NUMBER(12,2) DEFAULT 0,
    LAST_BILL_DATE DATE,
    CREATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE METER_READS (
    ID NUMBER(19) PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES ACCOUNTS(ID),
    METER_NUMBER VARCHAR2(30) NOT NULL,
    READING_VALUE NUMBER(14,3) NOT NULL,
    PREVIOUS_READING NUMBER(14,3),
    USAGE_KWH NUMBER(14,3),
    READ_TYPE VARCHAR2(20) NOT NULL,
    READ_DATE TIMESTAMP NOT NULL,
    VALIDATION_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    VALIDATION_MESSAGE VARCHAR2(500),
    BILLED NUMBER(1) DEFAULT 0
);

CREATE INDEX idx_meter_reads_account ON METER_READS(ACCOUNT_ID);
CREATE INDEX idx_meter_reads_date ON METER_READS(READ_DATE);
CREATE INDEX idx_meter_reads_unbilled ON METER_READS(ACCOUNT_ID, BILLED, VALIDATION_STATUS);

CREATE TABLE BILLS (
    ID NUMBER(19) PRIMARY KEY,
    BILL_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES ACCOUNTS(ID),
    PERIOD_START DATE NOT NULL,
    PERIOD_END DATE NOT NULL,
    USAGE_KWH NUMBER(14,3),
    BASE_CHARGE NUMBER(12,2) DEFAULT 0,
    USAGE_CHARGE NUMBER(12,2) DEFAULT 0,
    TAX_AMOUNT NUMBER(12,2) DEFAULT 0,
    TOTAL_AMOUNT NUMBER(12,2) DEFAULT 0,
    AMOUNT_PAID NUMBER(12,2) DEFAULT 0,
    BALANCE_DUE NUMBER(12,2) DEFAULT 0,
    DUE_DATE DATE,
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    TARIFF_CODE VARCHAR2(30),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX idx_bills_account ON BILLS(ACCOUNT_ID);
CREATE INDEX idx_bills_status ON BILLS(STATUS);
CREATE INDEX idx_bills_overdue ON BILLS(STATUS, DUE_DATE, BALANCE_DUE);

CREATE TABLE PAYMENTS (
    ID NUMBER(19) PRIMARY KEY,
    PAYMENT_REF VARCHAR2(50) NOT NULL UNIQUE,
    ACCOUNT_ID NUMBER(19) NOT NULL REFERENCES ACCOUNTS(ID),
    BILL_ID NUMBER(19) REFERENCES BILLS(ID),
    AMOUNT NUMBER(12,2) NOT NULL,
    PAYMENT_METHOD VARCHAR2(20),
    STATUS VARCHAR2(20) DEFAULT 'PENDING',
    TRANSACTION_DATE TIMESTAMP DEFAULT SYSTIMESTAMP,
    POSTED_DATE TIMESTAMP,
    EXTERNAL_REF VARCHAR2(100)
);

CREATE INDEX idx_payments_account ON PAYMENTS(ACCOUNT_ID);

CREATE TABLE TARIFFS (
    ID NUMBER(19) PRIMARY KEY,
    TARIFF_CODE VARCHAR2(30) NOT NULL,
    SERVICE_CLASS VARCHAR2(20) NOT NULL,
    BASE_CHARGE NUMBER(10,4),
    TIER1_LIMIT NUMBER(10),
    TIER1_RATE NUMBER(10,6),
    TIER2_LIMIT NUMBER(10),
    TIER2_RATE NUMBER(10,6),
    TIER3_RATE NUMBER(10,6),
    TAX_RATE NUMBER(8,6),
    SEASON VARCHAR2(10),
    EFFECTIVE_DATE DATE,
    EXPIRY_DATE DATE,
    GROOVY_SCRIPT_NAME VARCHAR2(100)
);

-- Insert default tariffs
INSERT INTO TARIFFS (ID, TARIFF_CODE, SERVICE_CLASS, BASE_CHARGE, TIER1_LIMIT, TIER1_RATE,
    TIER2_LIMIT, TIER2_RATE, TIER3_RATE, TAX_RATE, EFFECTIVE_DATE, GROOVY_SCRIPT_NAME)
VALUES (TARIFF_SEQ.NEXTVAL, 'RES-STANDARD', 'RESIDENTIAL', 12.50, 500, 0.082, 1000, 0.125,
    0.185, 0.087, DATE '2024-01-01', 'residential-rate');

INSERT INTO TARIFFS (ID, TARIFF_CODE, SERVICE_CLASS, BASE_CHARGE, TIER1_LIMIT, TIER1_RATE,
    TIER2_LIMIT, TIER2_RATE, TIER3_RATE, TAX_RATE, EFFECTIVE_DATE)
VALUES (TARIFF_SEQ.NEXTVAL, 'COM-STANDARD', 'COMMERCIAL', 45.00, 2000, 0.072, 5000, 0.095,
    0.135, 0.087, DATE '2024-01-01');

-- Materialized view for billing summary reporting
CREATE MATERIALIZED VIEW MV_BILLING_SUMMARY
BUILD IMMEDIATE REFRESH ON DEMAND AS
SELECT
    a.SERVICE_CLASS,
    a.BILLING_CYCLE,
    COUNT(DISTINCT a.ID) as ACCOUNT_COUNT,
    SUM(b.TOTAL_AMOUNT) as TOTAL_BILLED,
    SUM(b.AMOUNT_PAID) as TOTAL_COLLECTED,
    SUM(b.BALANCE_DUE) as TOTAL_OUTSTANDING
FROM ACCOUNTS a
LEFT JOIN BILLS b ON a.ID = b.ACCOUNT_ID
GROUP BY a.SERVICE_CLASS, a.BILLING_CYCLE;
